### ISSUE TITLE
Increase in gorouter memory with TLS enabled to Diego

### ISSUE THREAD

**Issue by Soha-Albaghdady** [cloudfoundry/gorouter#254]
## Issue

After updating to cf-deployment v11.0.0 (with route integrity enabled) on one of our productive landscapes, we have noticed an increase in the gorouter memory usage. The usage increases in steps as depicted below. It took almost a week till the usage rose to > 90%.

![Screen Shot 2019-08-28 at 09 01 16](https://user-images.githubusercontent.com/29755653/63859786-3efd7f00-c9a8-11e9-8369-e0925944b48d.png)

## Context
We are using gorouter within cf-deployment ( v11.0.0, routing-release v0.190.0). SSL is not terminated on the gorouter.

The memory usage increase was not observed directly after the update to cf-deployment v11.0.0 at that time the usage was about 15%. However, two days later the usage increased to ~ 28%. The memory usage remained the same for 3 days but increased afterwards reaching almost 60%. The third increase was observed a day later to 70 %. The increase in memory doesn't correlate to the `total_request` nor to the `total_routes`.

Nevertheless, at the time when memory increases, we see many occurrences of the following error in the logs:
```
2019/08/27 09:52:32 httputil: ReverseProxy read error during body copy: read tcp 10.0.129.11:27892->10.0.139.165:61074: use of closed network connection
```
See also:

![memory_increase](https://user-images.githubusercontent.com/29755653/63860562-a10ab400-c9a9-11e9-807a-591c1b375795.png) 
![logs_during_increase](https://user-images.githubusercontent.com/29755653/63860572-a536d180-c9a9-11e9-957a-e4bca4c26797.png)

In the specified timeframe, we saw ~30.000 occurrences of the error. Each gorouter showed 2.600 errors. The error occurs while trying to connect to different diego cells.

According to the heap profile taken with `pprof`, 51% is consumed by `bytes makeSlice` `tls(*Conn).readRecordOrCCS`. see:

![gorouter_heap](https://user-images.githubusercontent.com/29755653/63860814-1080a380-c9aa-11e9-9a8e-0fc404ffcb54.gif)
[heap.txt](https://github.com/cloudfoundry/gorouter/files/3551348/heap.txt)
[goroutines.txt](https://github.com/cloudfoundry/gorouter/files/3551351/goroutines.txt)

We have done the same update on our staging landscape before but haven't observed any memory increase. Hence, we believe that the issue is only visible with high load. In our productive setup we have 12 gorouter instances and the load ranges between 1K- 6k.

## Steps to Reproduce
We didn't manage to reproduce the issue on our test landscape.

## Expected result
A higher constant memory consumption due to enabling TLS routing. 

## Current result
Steady memory increase.

**Comment by GitPaddo** [comment]
Some more metadata on our update:

- cf-deployment was updated from v9.5 to v11.0
- Diego-release has been updated from 2.34.0 to 2.35.0
- Routing-release has been updated from 0.188.0 to 0.190.0

**Comment by rodolfo2488** [comment]
Hi @Soha-Albaghdady !

Thanks for filing this issue and including all of the information. We have started looking into this and have a couple of additional questions:

1. Are you using the default `cf-deployment.yml`? Are there any additional ops-files you apply?
1. Have you rolled back your production env as a result of the memory issues?

Thanks in advance,
@angelachin and @rodolfo2488 
CF Networking Team Members

**Comment by Soha-Albaghdady** [comment]
Hi @rodolfo2488, @angelachin,

Thank you for your reply.
Yes, we are using additional ops files. Following below are the (possibly) relevant properties that we change in our ops file for gorouter and diego cells.

```
- type: replace
  path: /instance_groups/name=router/jobs/name=sysctl?
  value:
    name: sysctl
    release: os-conf
    properties:
       sysctl:
       - net.ipv4.ip_local_port_range=1024 65535
       - net.ipv4.tcp_max_syn_backlog=4096
       - net.core.somaxconn=4096
- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/router/max_idle_connections?
  value: 49500

- type: remove
  path: /instance_groups/name=router/jobs/name=gorouter/properties/routing_api

- type: replace
  path: /instance_groups/name=diego-cell/jobs/name=sysctl?
  value:
    name: sysctl
    release: os-conf
    properties:
       sysctl:
       - net.ipv4.neigh.default.gc_thresh3=8192
       - net.ipv4.neigh.default.gc_thresh2=4096
       - net.ipv4.neigh.default.gc_thresh1=2048
```

For the second question, yes, we have rolled it back. Before rolling back we tried restarting the gorouters but we still experienced the same issue after the restart. 

BR,
Soha Albaghdady
