### ISSUE TITLE
gorouter pid file is missing

### ISSUE THREAD

**Issue by riuvshin** [cloudfoundry/gorouter#87]
Hi, Im trying to launch gorouter:
`/usr/local/gorouter/bin/gorouter -c="/usr/local/gorouter/gorouter.conf"`

with such configuration file:
```
status:
  port: 8282
  user: user
  pass: user

nats:
  - host: "localhost"
    port: 4222
    user:
    pass:

logging:
  file: /var/log/gorouter.log
  syslog: /var/log/gorouter.sys.log
  level: debug

port: 8081
index: 0
pidfile: /var/run/gorouter.pid
access_log: /var/log/gorouter.access.log
go_max_procs: 8

publish_start_message_interval: 30
prune_stale_droplets_interval: 30
droplet_stale_threshold: 120
publish_active_apps_interval: 0 # 0 means disabled
```

And I expect pidfile at /var/run/gorouter.pid but pidfile is **missing**.
**syslog** file is missing also.

  file: /var/log/gorouter.log and access_log: /var/log/gorouter.access.log are ok.

I've build from this commit https://github.com/cloudfoundry/gorouter/commit/76668f5818ea8c089ff52a14fcdfbf703c8e8767
